### ISSUE TITLE
Improve subscription results

### ISSUE THREAD

**Issue by helios1138** [prisma/graphql-playground#1045]
Currently, subscription results are very hard to use due to:
1. [issue](https://github.com/prisma/graphql-playground/issues/1021) that makes scrolling through them impossible
2. They are displayed older-first instead of newer-first

Which means if I just want to watch the latest values, I have no way of doing that.

Proposed solution (until solutions to issues mentioned above are implemented): add an option to switch from a list to show only the latest result all the time, the way it's done in GraphiQL

**Comment by lPaths** [comment]
any news on this? i saw it opened 29days ago..

**Comment by dariadomagala** [comment]
Hello, are there any updates on that issue?

**Comment by ksugiarto** [comment]
No update on this issue? Then how did you guys use this for Subscription all this long? Any workaround?

**Comment by dehypnosis** [comment]
can try a workaround
```css
  .graphiql-wrapper>div:first-child>div:first-child>div:nth-child(2) {
    height: 100% !important;
  }
  .graphiql-wrapper>div:first-child>div:first-child>div:nth-child(2)>div:nth-child(2) {
    height: 100% !important;
  }
```
