### ISSUE TITLE
Saving a workspace will overwrite .graphqlconfig.yml with JSON data

### ISSUE THREAD

**Issue by berstend** [prisma/graphql-playground#820]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

macOS

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

Version 1.6.2 (1.6.2.3788)

#### What is the expected behavior?

When hitting `cmd+s` the Playground app should not overwrite the `.graphqlconfig.yml` file with JSON data (it should use YAML).

#### What is the actual behavior?

When hitting `cmd+s` the Playground app is overwriting the `.graphqlconfig.yml` file with JSON data.

#### What steps may we take to reproduce the behavior?

* Use a `.graphqlconfig.yml` file
* Run `graphql playground`
* Save the workspace (`cmd + s`)
* Inspect `.graphqlconfig.yml` file

_Please provide a gif or image of the issue for a quicker response/fix._
![image](https://user-images.githubusercontent.com/1368633/44273037-a386e980-a23e-11e8-851c-c8b59b4aecba.png)

**Comment by berstend** [comment]
Actually it's not only yaml vs. json, the data itself seems to get corrupted as well.

Before:

```yaml
projects:
  database:
    schemaPath: src/common/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/common/generated/prisma.ts
```

After saving the workspace in Playground:

```json
{"schemaPath":"","projects":{"default":{"schemaPath":"","extensions":{"endpoints":{"default":{"url":"http://localhost:4466"}}}}}}
```
